---
- hosts: 172.31.43.141
  become: yes
  tasks:
  - name: i want install direct linux  command
    command: hostname -f 
    register: myresult

  - name: i want to see first task result 
    debug: 
      msg: "{{myresult}}"
    