---
- hosts: 172.31.43.141
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: i want to copy file  into node side
    copy:
       src: mytestfile
       dest: /home/maha/mytestfile
    notify: startwebserver

  - name: install apache2 
    apt: 
      name: apache2
      state: present 
    notify: startwebserver

  - name: copy myindex file into node side 
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: startwebserver
    
  - name: download internet file
    get_url:
       url: https://github.com/maha4dsvc/mahalogin/blob/master/target/mahaLogin-2.0.war
       dest: /home/maha/mahaLogin-2.0.war
       force_basic_auth: yes

  handlers: 
  - name: startwebserver
    service:
       name: apache2
       state: started
    
       
    

