---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu nodes
    apt:
      name: apache2
      state: present
    
  - name: i want to start my webserver on nodes
    service:
       name: apache2
       state: started
